// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SfUPRNStatusResponse.proto

package nyy.roar.jfl.poc.kafka.protobuf.uprn;

/**
 * Protobuf type {@code statusChange.Payload}
 */
public final class Payload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:statusChange.Payload)
    PayloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Payload.newBuilder() to construct.
  private Payload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Payload() {
    uprn_ = "";
    uprnStatus_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Payload();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Payload(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            uprn_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            uprnStatus_ = rawValue;
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (date1_ != null) {
              subBuilder = date1_.toBuilder();
            }
            date1_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(date1_);
              date1_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return nyy.roar.jfl.poc.kafka.protobuf.uprn.UPRNStatusProtos.internal_static_statusChange_Payload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return nyy.roar.jfl.poc.kafka.protobuf.uprn.UPRNStatusProtos.internal_static_statusChange_Payload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.class, nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.Builder.class);
  }

  /**
   * Protobuf enum {@code statusChange.Payload.UPRNStatus}
   */
  public enum UPRNStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>START_ORDER_A = 0;</code>
     */
    START_ORDER_A(0),
    /**
     * <code>START_ORDER_B = 1;</code>
     */
    START_ORDER_B(1),
    /**
     * <code>START_ORDER_C = 2;</code>
     */
    START_ORDER_C(2),
    /**
     * <code>REGISTER_INTEREST_COMMITTED_BUILD_A = 3;</code>
     */
    REGISTER_INTEREST_COMMITTED_BUILD_A(3),
    /**
     * <code>REGISTER_INTEREST_COMMITTED_BUILD_B = 4;</code>
     */
    REGISTER_INTEREST_COMMITTED_BUILD_B(4),
    /**
     * <code>REGISTER_INTEREST_COMMITTED_BUILD_C = 5;</code>
     */
    REGISTER_INTEREST_COMMITTED_BUILD_C(5),
    /**
     * <code>REGISTER_INTEREST_COMMITTED_BUILD = 6;</code>
     */
    REGISTER_INTEREST_COMMITTED_BUILD(6),
    /**
     * <code>REGISTER_INTEREST_CONSTRUCTION_DELAY = 7;</code>
     */
    REGISTER_INTEREST_CONSTRUCTION_DELAY(7),
    /**
     * <code>INVITED_TO_CALL_IN = 8;</code>
     */
    INVITED_TO_CALL_IN(8),
    /**
     * <code>REGISTER_INTEREST_LIMITED_CAPACITY = 9;</code>
     */
    REGISTER_INTEREST_LIMITED_CAPACITY(9),
    /**
     * <code>REGISTER_INTEREST_ONPLAN_WITH_DATE = 10;</code>
     */
    REGISTER_INTEREST_ONPLAN_WITH_DATE(10),
    /**
     * <code>REGISTER_INTEREST_ONPLAN_WITHOUT_DATE = 11;</code>
     */
    REGISTER_INTEREST_ONPLAN_WITHOUT_DATE(11),
    /**
     * <code>REGISTER_INTEREST_OFFPLAN = 12;</code>
     */
    REGISTER_INTEREST_OFFPLAN(12),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>START_ORDER_A = 0;</code>
     */
    public static final int START_ORDER_A_VALUE = 0;
    /**
     * <code>START_ORDER_B = 1;</code>
     */
    public static final int START_ORDER_B_VALUE = 1;
    /**
     * <code>START_ORDER_C = 2;</code>
     */
    public static final int START_ORDER_C_VALUE = 2;
    /**
     * <code>REGISTER_INTEREST_COMMITTED_BUILD_A = 3;</code>
     */
    public static final int REGISTER_INTEREST_COMMITTED_BUILD_A_VALUE = 3;
    /**
     * <code>REGISTER_INTEREST_COMMITTED_BUILD_B = 4;</code>
     */
    public static final int REGISTER_INTEREST_COMMITTED_BUILD_B_VALUE = 4;
    /**
     * <code>REGISTER_INTEREST_COMMITTED_BUILD_C = 5;</code>
     */
    public static final int REGISTER_INTEREST_COMMITTED_BUILD_C_VALUE = 5;
    /**
     * <code>REGISTER_INTEREST_COMMITTED_BUILD = 6;</code>
     */
    public static final int REGISTER_INTEREST_COMMITTED_BUILD_VALUE = 6;
    /**
     * <code>REGISTER_INTEREST_CONSTRUCTION_DELAY = 7;</code>
     */
    public static final int REGISTER_INTEREST_CONSTRUCTION_DELAY_VALUE = 7;
    /**
     * <code>INVITED_TO_CALL_IN = 8;</code>
     */
    public static final int INVITED_TO_CALL_IN_VALUE = 8;
    /**
     * <code>REGISTER_INTEREST_LIMITED_CAPACITY = 9;</code>
     */
    public static final int REGISTER_INTEREST_LIMITED_CAPACITY_VALUE = 9;
    /**
     * <code>REGISTER_INTEREST_ONPLAN_WITH_DATE = 10;</code>
     */
    public static final int REGISTER_INTEREST_ONPLAN_WITH_DATE_VALUE = 10;
    /**
     * <code>REGISTER_INTEREST_ONPLAN_WITHOUT_DATE = 11;</code>
     */
    public static final int REGISTER_INTEREST_ONPLAN_WITHOUT_DATE_VALUE = 11;
    /**
     * <code>REGISTER_INTEREST_OFFPLAN = 12;</code>
     */
    public static final int REGISTER_INTEREST_OFFPLAN_VALUE = 12;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UPRNStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UPRNStatus forNumber(int value) {
      switch (value) {
        case 0: return START_ORDER_A;
        case 1: return START_ORDER_B;
        case 2: return START_ORDER_C;
        case 3: return REGISTER_INTEREST_COMMITTED_BUILD_A;
        case 4: return REGISTER_INTEREST_COMMITTED_BUILD_B;
        case 5: return REGISTER_INTEREST_COMMITTED_BUILD_C;
        case 6: return REGISTER_INTEREST_COMMITTED_BUILD;
        case 7: return REGISTER_INTEREST_CONSTRUCTION_DELAY;
        case 8: return INVITED_TO_CALL_IN;
        case 9: return REGISTER_INTEREST_LIMITED_CAPACITY;
        case 10: return REGISTER_INTEREST_ONPLAN_WITH_DATE;
        case 11: return REGISTER_INTEREST_ONPLAN_WITHOUT_DATE;
        case 12: return REGISTER_INTEREST_OFFPLAN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UPRNStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UPRNStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UPRNStatus>() {
            public UPRNStatus findValueByNumber(int number) {
              return UPRNStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.getDescriptor().getEnumTypes().get(0);
    }

    private static final UPRNStatus[] VALUES = values();

    public static UPRNStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UPRNStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:statusChange.Payload.UPRNStatus)
  }

  public static final int UPRN_FIELD_NUMBER = 1;
  private volatile java.lang.Object uprn_;
  /**
   * <code>string uprn = 1;</code>
   * @return The uprn.
   */
  @java.lang.Override
  public java.lang.String getUprn() {
    java.lang.Object ref = uprn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uprn_ = s;
      return s;
    }
  }
  /**
   * <code>string uprn = 1;</code>
   * @return The bytes for uprn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUprnBytes() {
    java.lang.Object ref = uprn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uprn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPRNSTATUS_FIELD_NUMBER = 2;
  private int uprnStatus_;
  /**
   * <code>.statusChange.Payload.UPRNStatus uprnStatus = 2;</code>
   * @return The enum numeric value on the wire for uprnStatus.
   */
  @java.lang.Override public int getUprnStatusValue() {
    return uprnStatus_;
  }
  /**
   * <code>.statusChange.Payload.UPRNStatus uprnStatus = 2;</code>
   * @return The uprnStatus.
   */
  @java.lang.Override public nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.UPRNStatus getUprnStatus() {
    @SuppressWarnings("deprecation")
    nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.UPRNStatus result = nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.UPRNStatus.valueOf(uprnStatus_);
    return result == null ? nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.UPRNStatus.UNRECOGNIZED : result;
  }

  public static final int DATE1_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp date1_;
  /**
   * <code>.google.protobuf.Timestamp date1 = 3;</code>
   * @return Whether the date1 field is set.
   */
  @java.lang.Override
  public boolean hasDate1() {
    return date1_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp date1 = 3;</code>
   * @return The date1.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDate1() {
    return date1_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date1_;
  }
  /**
   * <code>.google.protobuf.Timestamp date1 = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDate1OrBuilder() {
    return getDate1();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uprn_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uprn_);
    }
    if (uprnStatus_ != nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.UPRNStatus.START_ORDER_A.getNumber()) {
      output.writeEnum(2, uprnStatus_);
    }
    if (date1_ != null) {
      output.writeMessage(3, getDate1());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uprn_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uprn_);
    }
    if (uprnStatus_ != nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.UPRNStatus.START_ORDER_A.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, uprnStatus_);
    }
    if (date1_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDate1());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload)) {
      return super.equals(obj);
    }
    nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload other = (nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload) obj;

    if (!getUprn()
        .equals(other.getUprn())) return false;
    if (uprnStatus_ != other.uprnStatus_) return false;
    if (hasDate1() != other.hasDate1()) return false;
    if (hasDate1()) {
      if (!getDate1()
          .equals(other.getDate1())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UPRN_FIELD_NUMBER;
    hash = (53 * hash) + getUprn().hashCode();
    hash = (37 * hash) + UPRNSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + uprnStatus_;
    if (hasDate1()) {
      hash = (37 * hash) + DATE1_FIELD_NUMBER;
      hash = (53 * hash) + getDate1().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code statusChange.Payload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:statusChange.Payload)
      nyy.roar.jfl.poc.kafka.protobuf.uprn.PayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nyy.roar.jfl.poc.kafka.protobuf.uprn.UPRNStatusProtos.internal_static_statusChange_Payload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nyy.roar.jfl.poc.kafka.protobuf.uprn.UPRNStatusProtos.internal_static_statusChange_Payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.class, nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.Builder.class);
    }

    // Construct using nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uprn_ = "";

      uprnStatus_ = 0;

      if (date1Builder_ == null) {
        date1_ = null;
      } else {
        date1_ = null;
        date1Builder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return nyy.roar.jfl.poc.kafka.protobuf.uprn.UPRNStatusProtos.internal_static_statusChange_Payload_descriptor;
    }

    @java.lang.Override
    public nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload getDefaultInstanceForType() {
      return nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.getDefaultInstance();
    }

    @java.lang.Override
    public nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload build() {
      nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload buildPartial() {
      nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload result = new nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload(this);
      result.uprn_ = uprn_;
      result.uprnStatus_ = uprnStatus_;
      if (date1Builder_ == null) {
        result.date1_ = date1_;
      } else {
        result.date1_ = date1Builder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload) {
        return mergeFrom((nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload other) {
      if (other == nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.getDefaultInstance()) return this;
      if (!other.getUprn().isEmpty()) {
        uprn_ = other.uprn_;
        onChanged();
      }
      if (other.uprnStatus_ != 0) {
        setUprnStatusValue(other.getUprnStatusValue());
      }
      if (other.hasDate1()) {
        mergeDate1(other.getDate1());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object uprn_ = "";
    /**
     * <code>string uprn = 1;</code>
     * @return The uprn.
     */
    public java.lang.String getUprn() {
      java.lang.Object ref = uprn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uprn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uprn = 1;</code>
     * @return The bytes for uprn.
     */
    public com.google.protobuf.ByteString
        getUprnBytes() {
      java.lang.Object ref = uprn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uprn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uprn = 1;</code>
     * @param value The uprn to set.
     * @return This builder for chaining.
     */
    public Builder setUprn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uprn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string uprn = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUprn() {
      
      uprn_ = getDefaultInstance().getUprn();
      onChanged();
      return this;
    }
    /**
     * <code>string uprn = 1;</code>
     * @param value The bytes for uprn to set.
     * @return This builder for chaining.
     */
    public Builder setUprnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uprn_ = value;
      onChanged();
      return this;
    }

    private int uprnStatus_ = 0;
    /**
     * <code>.statusChange.Payload.UPRNStatus uprnStatus = 2;</code>
     * @return The enum numeric value on the wire for uprnStatus.
     */
    @java.lang.Override public int getUprnStatusValue() {
      return uprnStatus_;
    }
    /**
     * <code>.statusChange.Payload.UPRNStatus uprnStatus = 2;</code>
     * @param value The enum numeric value on the wire for uprnStatus to set.
     * @return This builder for chaining.
     */
    public Builder setUprnStatusValue(int value) {
      
      uprnStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.statusChange.Payload.UPRNStatus uprnStatus = 2;</code>
     * @return The uprnStatus.
     */
    @java.lang.Override
    public nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.UPRNStatus getUprnStatus() {
      @SuppressWarnings("deprecation")
      nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.UPRNStatus result = nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.UPRNStatus.valueOf(uprnStatus_);
      return result == null ? nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.UPRNStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.statusChange.Payload.UPRNStatus uprnStatus = 2;</code>
     * @param value The uprnStatus to set.
     * @return This builder for chaining.
     */
    public Builder setUprnStatus(nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.UPRNStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      uprnStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.statusChange.Payload.UPRNStatus uprnStatus = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUprnStatus() {
      
      uprnStatus_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp date1_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> date1Builder_;
    /**
     * <code>.google.protobuf.Timestamp date1 = 3;</code>
     * @return Whether the date1 field is set.
     */
    public boolean hasDate1() {
      return date1Builder_ != null || date1_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp date1 = 3;</code>
     * @return The date1.
     */
    public com.google.protobuf.Timestamp getDate1() {
      if (date1Builder_ == null) {
        return date1_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date1_;
      } else {
        return date1Builder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp date1 = 3;</code>
     */
    public Builder setDate1(com.google.protobuf.Timestamp value) {
      if (date1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        date1_ = value;
        onChanged();
      } else {
        date1Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date1 = 3;</code>
     */
    public Builder setDate1(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (date1Builder_ == null) {
        date1_ = builderForValue.build();
        onChanged();
      } else {
        date1Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date1 = 3;</code>
     */
    public Builder mergeDate1(com.google.protobuf.Timestamp value) {
      if (date1Builder_ == null) {
        if (date1_ != null) {
          date1_ =
            com.google.protobuf.Timestamp.newBuilder(date1_).mergeFrom(value).buildPartial();
        } else {
          date1_ = value;
        }
        onChanged();
      } else {
        date1Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date1 = 3;</code>
     */
    public Builder clearDate1() {
      if (date1Builder_ == null) {
        date1_ = null;
        onChanged();
      } else {
        date1_ = null;
        date1Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date1 = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDate1Builder() {
      
      onChanged();
      return getDate1FieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp date1 = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDate1OrBuilder() {
      if (date1Builder_ != null) {
        return date1Builder_.getMessageOrBuilder();
      } else {
        return date1_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : date1_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp date1 = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDate1FieldBuilder() {
      if (date1Builder_ == null) {
        date1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDate1(),
                getParentForChildren(),
                isClean());
        date1_ = null;
      }
      return date1Builder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:statusChange.Payload)
  }

  // @@protoc_insertion_point(class_scope:statusChange.Payload)
  private static final nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload();
  }

  public static nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Payload>
      PARSER = new com.google.protobuf.AbstractParser<Payload>() {
    @java.lang.Override
    public Payload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Payload(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Payload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Payload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

