// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SfUPRNStatusResponse.proto

package nyy.roar.jfl.poc.kafka.protobuf.uprn;

public interface PayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:statusChange.Payload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uprn = 1;</code>
   * @return The uprn.
   */
  java.lang.String getUprn();
  /**
   * <code>string uprn = 1;</code>
   * @return The bytes for uprn.
   */
  com.google.protobuf.ByteString
      getUprnBytes();

  /**
   * <code>.statusChange.Payload.UPRNStatus uprnStatus = 2;</code>
   * @return The enum numeric value on the wire for uprnStatus.
   */
  int getUprnStatusValue();
  /**
   * <code>.statusChange.Payload.UPRNStatus uprnStatus = 2;</code>
   * @return The uprnStatus.
   */
  nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload.UPRNStatus getUprnStatus();

  /**
   * <code>.google.protobuf.Timestamp date1 = 3;</code>
   * @return Whether the date1 field is set.
   */
  boolean hasDate1();
  /**
   * <code>.google.protobuf.Timestamp date1 = 3;</code>
   * @return The date1.
   */
  com.google.protobuf.Timestamp getDate1();
  /**
   * <code>.google.protobuf.Timestamp date1 = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDate1OrBuilder();
}
