// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SfUPRNStatusResponse.proto

package nyy.roar.jfl.poc.kafka.protobuf.uprn;

public interface StatusEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:statusChange.StatusEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message_type__c = 1;</code>
   * @return The messageTypeC.
   */
  java.lang.String getMessageTypeC();
  /**
   * <code>string message_type__c = 1;</code>
   * @return The bytes for messageTypeC.
   */
  com.google.protobuf.ByteString
      getMessageTypeCBytes();

  /**
   * <code>.statusChange.Payload payload__c = 2;</code>
   * @return Whether the payloadC field is set.
   */
  boolean hasPayloadC();
  /**
   * <code>.statusChange.Payload payload__c = 2;</code>
   * @return The payloadC.
   */
  nyy.roar.jfl.poc.kafka.protobuf.uprn.Payload getPayloadC();
  /**
   * <code>.statusChange.Payload payload__c = 2;</code>
   */
  nyy.roar.jfl.poc.kafka.protobuf.uprn.PayloadOrBuilder getPayloadCOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp event_date__c = 3;</code>
   * @return Whether the eventDateC field is set.
   */
  boolean hasEventDateC();
  /**
   * <code>.google.protobuf.Timestamp event_date__c = 3;</code>
   * @return The eventDateC.
   */
  com.google.protobuf.Timestamp getEventDateC();
  /**
   * <code>.google.protobuf.Timestamp event_date__c = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEventDateCOrBuilder();

  /**
   * <code>string test_string__c = 4;</code>
   * @return The testStringC.
   */
  java.lang.String getTestStringC();
  /**
   * <code>string test_string__c = 4;</code>
   * @return The bytes for testStringC.
   */
  com.google.protobuf.ByteString
      getTestStringCBytes();
}
